---
# tasks file for ansible-role-mcafee-endpoint-security

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/{{ package_name.split('-')[0] }}/"
    state: directory
  
- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/{{ package_name.split('-')[0] }}/{{ package_name }}"
  register: package

- name: "Download & Extract installer package from local repository"
  ansible.builtin.unarchive:
    src: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/{{ package_name.split('-')[0] }}/"
    validate_certs: no
    mode: 0777
    remote_src: yes
  when: package.stat.exists != True

- name: "Install package"
  ansible.builtin.command: "./install-mfetp.sh silent"
  args:
    chdir: "/root/software/{{ package_name.split('-')[0] }}/"
    creates: /var/McAfee/ens/esp/prefs.xml
