---
# tasks file for ansible-role-mcafee-endpoint-security

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: item|string not in ansible_facts.packages
  with_items: "{{ packages }}"

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/mcafee-epo/"
    state: directory

- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/mcafee-epo/{{ package_name }}"
  register: package

- name: "Download & Extract installer package from local repository"
  ansible.builtin.unarchive:
    src: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/mcafee-epo/"
    validate_certs: no
    mode: '0770'
    remote_src: yes
  when: package.stat.exists != True

- name: "Install package"
  ansible.builtin.command: "./install-mfetp.sh silent"
  args:
    chdir: "/root/software/mcafee-epo/"
    creates: /var/McAfee/ens/esp/prefs.xml

- name: "Disable On-Access Scanning"
  ansible.builtin.command: "./mfetpcli --setoasglobalconfig --oas off"
  args:
    chdir: "/opt/McAfee/ens/tp/bin"
